server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  security:
    user:
      name: baige
      password: 123456
management:
  server:
    port: 8090
    base-path: /sys
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'