server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: "http:localhost://8080"
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  security:
    user:
      name: xkcoding
      password: 123456
  management:
    endpoint:
      health:
        # ??????????"never"????"always"???????????????
        show-details: always
    endpoints:
      web:
        exposure:
          # ??????????????["health","info"]???"*"????????????
          include: "*"

